### ISSUE TITLE
config is not in list

### ISSUE THREAD

**Issue by xuhuiling999** [greatlog/UnpairedSR#34]
作者你好，请问我在train 2018track2.yml时报错如下：
Traceback (most recent call last):
  File "train.py", line 412, in <module>
    main()
  File "train.py", line 114, in main
    opt = option.parse(args.opt, args.root_path, is_train=True)
  File "E:\sr2022\PDMSR\util_s\option.py", line 60, in parse
    config_dir = config_paths[config_paths.index("config") + 1]
ValueError: 'config' is not in list
您知道是什么问题吗？

**Comment by cgysjy** [comment]
您好，我也遇到了这个问题，请问您怎么解决的呢
