### ISSUE TITLE
在run test.py时遇到了下面的错误

### ISSUE THREAD

**Issue by Fangzhenxuan** [greatlog/UnpairedSR#5]
Traceback (most recent call last):
  File "D:/Fang/study/my_code/Unsupervise_KE/KEGAN/codes/config/PDM-SR/test.py", line 296, in <module>
    main()
  File "D:/Fang/study/my_code/Unsupervise_KE/KEGAN/codes/config/PDM-SR/test.py", line 81, in main
    main_worker(0, 1, opt, args)
  File "D:/Fang/study/my_code/Unsupervise_KE/KEGAN/codes/config/PDM-SR/test.py", line 161, in main_worker
    logger,
  File "D:/Fang/study/my_code/Unsupervise_KE/KEGAN/codes/config/PDM-SR/test.py", line 228, in validate
    scores = measure(res=cropped_sr_img, ref=cropped_gt_img, metrics=opt["metrics"])
  File "D:\Fang\study\my_code\Unsupervise_KE\KEGAN\codes\metrics\measure.py", line 57, in __call__
    scores[metric] = getattr(self, "calculate_{}".format(metric))(res)
  File "D:\Fang\study\my_code\Unsupervise_KE\KEGAN\codes\metrics\measure.py", line 79, in calculate_niqe
    return self.eng.niqe(self.matlab_res)
  File "D:\Fang\study\python37\lib\site-packages\matlab\engine\matlabengine.py", line 71, in __call__
    _stderr, feval=True).result()
  File "D:\Fang\study\python37\lib\site-packages\matlab\engine\futureresult.py", line 67, in result
    return self.__future.result(timeout)
  File "D:\Fang\study\python37\lib\site-packages\matlab\engine\fevalfuture.py", line 82, in result
    self._result = pythonengine.getFEvalResult(self._future,self._nargout, None, out=self._out, err=self._err)
matlab.engine.MatlabExecutionError: 未定义与 'uint8' 类型的输入参数相对应的函数 'niqe'。

请问一下作者遇到过吗，怎么解决？
matlab版本是2021b

**Comment by greatlog** [comment]
我没有遇到过类似的问题，看起来是matlab中没有对应函数，你可以单独在你的matlab命令行试试niqe函数是否可以正常使用，然后检查一下Python对matlab的接口是否正常安装。

**Comment by Fangzhenxuan** [comment]
已经解决了，谢谢

**Comment by alec-97** [comment]
> 

您好，请问这个问题是怎么解决的呢？我也遇到了同样问题，期待您的回复
