### ISSUE TITLE
运行inference.py时遇到KeyError: 'netDeg'错误

### ISSUE THREAD

**Issue by LiYAnErr** [greatlog/UnpairedSR#7]
作者您好，我按照“Start up”里的指引，运行inference.py时遇到了下面的错误，请问您知道这是什么地方出现了问题吗？十分感谢！

Traceback (most recent call last):
  File "inference.py", line 57, in <module>
    model.test({"src": img_t}, crop_size=512)
  File "/6T/home/dell/LiYAnErr/20220312/UnpairedSR-master/codes/config/PDM-SR/models/deg_sr_model.py", line 264, in test
    self.set_network_state(["netDeg", "netSR"], "eval")
  File "/6T/home/dell/LiYAnErr/20220312/UnpairedSR-master/codes/config/PDM-SR/models/base_model.py", line 184, in set_network_state
    if isinstance(self.networks[name], nn.Module):
KeyError: 'netDeg'

**Comment by greatlog** [comment]
可更新代码后重试

**Comment by qiqi450** [comment]
> 

你好，请问解决了吗，我也遇到了同样的问题
